# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user_name: user
  password: password

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  user_name: user
  password: password

test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  user_name: user
  password: password

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  user_name: user
  password: password
